WebApplication1/Controllers/View/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplication1.Models.IdentityModels;
using WebApplication1.Data;
using X.PagedList;
using WebApplication1.Models.QuestionsAndAnswers;

namespace WebApplication1.Controllers
{
    [Authorize(Roles = "Administrator")]
    [Route("[controller]/[action]")]
    public class AdminController : Controller
    {
        private ApplicationDbContext _db;
        private UserManager<ApplicationUser> _userManager;
        private RoleManager<IdentityRole> _roleManager;
        public AdminController(UserManager<ApplicationUser> manager, 
                               RoleManager<IdentityRole> roleManager, 
                               ApplicationDbContext db)
        {
            _db = db;
            _userManager = manager;
            _roleManager = roleManager;
        }
        #region public IActionResult MainUsers(string searchStringUserNameOrEmail)
        public async Task<ActionResult> Index(string searchStringUserNameOrEmail, string currentFilter, int? page)
        {
            try
            {
                int intPage = 1;
                int intPageSize = 15;
                int intTotalPageCount = 0;

                if (searchStringUserNameOrEmail != null)
                {
                    intPage = 1;
                }
                else
                {
                    if (currentFilter != null)
                    {
                        searchStringUserNameOrEmail = currentFilter;
                        intPage = page ?? 1;
                    }
                    else
                    {
                        searchStringUserNameOrEmail = "";
                        intPage = page ?? 1;
                    }
                }

                ViewBag.CurrentFilter = searchStringUserNameOrEmail;

                List<ExpandedUserDTO> col_UserDTO = new List<ExpandedUserDTO>();
                int intSkip = (intPage - 1) * intPageSize;

                intTotalPageCount = _userManager.Users
                    .Where(x => x.UserName.Contains(searchStringUserNameOrEmail) && x.Deleted != true && x.External == false)
                    .Count();

                var result = _userManager.Users
                    .Where(x => x.UserName.Contains(searchStringUserNameOrEmail) && x.Deleted != true && x.External == false)
                    .OrderBy(x => x.UserName)
                    .Skip(intSkip)
                    .Take(intPageSize)
                    .ToList();

                foreach (var item in result)
                {
                    ExpandedUserDTO objUserDTO = new ExpandedUserDTO();
                    objUserDTO.UserName = item.UserName;
                    objUserDTO.Email = item.Email;

                    col_UserDTO.Add(objUserDTO);
                }

                // Set the number of pages
                var _UserDTOAsIPagedList =
                    new StaticPagedList<ExpandedUserDTO>
                    (
                        col_UserDTO, intPage, intPageSize, intTotalPageCount
                        );

                return View(_UserDTOAsIPagedList);
            }
            catch (Exception ex)
            {
                var rr = ex;
                ModelState.AddModelError(string.Empty, "Error: " + ex);
                List<ExpandedUserDTO> col_UserDTO = new List<ExpandedUserDTO>();

                return View(col_UserDTO.ToPagedList(1, 25));

            }
        }
        #endregion

        // Users *****************************

        // PUT: /Admin/Create

        #region public async Task<IActionResult> Create(ExpandedUserDTO paramExpandedUserDTO)

     
        public async Task<ActionResult> Create()
        {
            ExpandedUserDTO objExpandedUserDTO = new ExpandedUserDTO();
            ViewBag.Roles = _db.Roles.ToList();

            return View(objExpandedUserDTO);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ExpandedUserDTO paramExpandedUserDTO)
        {
            try
            {
                if (paramExpandedUserDTO == null)
                {
                    return RedirectToAction("Error", "Home");
                }

                var checkUserName = await _userManager.FindByNameAsync(paramExpandedUserDTO.UserName);
                if (checkUserName != null)
                {
                    string message = "The name has already been used. Please use another one";
                    return RedirectToAction("ErrorPage", "Home", new { message = message });
                }

                var Email = paramExpandedUserDTO.Email;
                var UserName = paramExpandedUserDTO.UserName;
                var Password = paramExpandedUserDTO.Password;
                var Role = paramExpandedUserDTO.Role;

                if (Email == "" || Email == null)
                {
                    return RedirectToAction("Error", "Home");
                }

                if (UserName == "" || UserName == null)
                {
                    return RedirectToAction("Error", "Home");
                }

                if (Password == "" || Password == null)
                {
                    return RedirectToAction("Error", "Home");
                }

                var objNewAdminUser = new ApplicationUser
                {
                    UserName = UserName,
                    Email = Email,
                    External = false,
                    SecondName = paramExpandedUserDTO.SecondName,
                    FirstName = paramExpandedUserDTO.FirstName,
                    BirthDate = paramExpandedUserDTO.BirthDate
                };
                var AdminUserCreateResult = await _userManager.CreateAsync(objNewAdminUser, Password);

                if (AdminUserCreateResult.Succeeded == true)
                {
                    if (Role != null)
                        await _userManager.AddToRoleAsync(objNewAdminUser, Role);
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("ErrorPage", "Home");
                }
            }
            catch (Exception ex)
            {
                ViewBag.Roles = GetAllRolesAsSelectList();
                return RedirectToAction("ErrorPage", "Home");
            }
        }
        #endregion

        #region private void DeleteUser(string UserName)
        public async Task<ActionResult> DeleteUser(string UserName)
        {
            ApplicationUser user =
                _userManager.FindByNameAsync(UserName).Result;

            if (user == null)
            {
                throw new Exception("Could not find the User");
            }
            user.DeletedAt = DateTime.Now;
            user.Deleted = true;
            await _userManager.UpdateAsync(user);
            return RedirectToAction("Index");
        }
        #endregion

        // PUT: /Admin/EditUser
        #region public async Task<ActionResult> EditUser(ExpandedUserDTO pass)
        public async Task<ActionResult> EditUser(string UserName)
        {
            if (UserName == null)
            {
                return BadRequest();
            }
            ExpandedUserDTO objExpandedUserDTO = GetUser(UserName);
            if (objExpandedUserDTO == null)
            {
                return NotFound();
            }
            return View(objExpandedUserDTO);
        }
        [HttpPost]
        public async Task<ActionResult> EditUser(ExpandedUserDTO paramExpandedUserDTO)
        {
            if (paramExpandedUserDTO == null)
            {
                return BadRequest();
            }


            try
            {
                ApplicationUser result = await  _userManager.FindByNameAsync(paramExpandedUserDTO.UserName);
                result.Email = paramExpandedUserDTO.Email;
                if (await _userManager.IsLockedOutAsync(result))
                {
                    // Unlock user
                    await _userManager.ResetAccessFailedCountAsync(result);
                }

                await _userManager.UpdateAsync(result);
                if (!string.IsNullOrEmpty(paramExpandedUserDTO.Password))
                {
                    // Remove current password
                    await _userManager.RemovePasswordAsync(result);
                    await _userManager.AddPasswordAsync(result, paramExpandedUserDTO.Password);
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home");
            }

            return RedirectToAction("Index");
        }
        #endregion

        // PUT: /Admin/EditRoles/TestUser 

        #region public async Task<ActionResult> EditRoles(UserAndRolesDTO paramUserAndRolesDTO)
        public async Task<ActionResult> EditRoles(string UserName)
        {
            if (UserName == null)
            {
                return BadRequest();
            }

            UserName = UserName.ToLower();

            // Check that we have an actual user
            ExpandedUserDTO objExpandedUserDTO = GetUser(UserName);

            if (objExpandedUserDTO == null)
            {
                return NotFound();
            }

            UserAndRolesDTO objUserAndRolesDTO =
                GetUserAndRoles(UserName);

            return View(objUserAndRolesDTO);
        }

        [HttpPost]
        public async Task<ActionResult> EditRoles(UserAndRolesDTO paramUserAndRolesDTO)
        {
            try
            {
                if (paramUserAndRolesDTO == null)
                {
                    return new StatusCodeResult(StatusCodes.Status400BadRequest);
                }

                string UserName = paramUserAndRolesDTO.UserName;
                string strNewRole = Convert.ToString(Request.Form["AddRole"]);

WebApplication1/Views/Admin/AddRole.cshtml
@model WebApplication1.Models.IdentityModels.RoleDTO
@{
    ViewBag.Title = "AddRole";
    Layout = "_AdminLayout";
}
@using (Html.BeginForm())
{
    <div class="content-wrapper">
        <div class="card">
            <section class="content-header">
                <h1>
                    Roles
                    <small></small>
                </h1>
            </section>
            <br />
            @Html.AntiForgeryToken()
            <div class="card-primary">
                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.Label("Role name", "Role name",
                       htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.RoleName,
                           new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.RoleName,
                           "",
                           new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-default" />
                            @Html.ActionLink("Back",
                           "ViewAllRoles","admin",
                           null,
                           new { @class = "btn btn-default" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

WebApplication1/Views/Admin/Create.cshtml
@model WebApplication1.Models.IdentityModels.ExpandedUserDTO
@{
    ViewBag.Title = "Create";
    Layout = "_AdminLayout";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="content-wrapper">
        <div class="card-body">
            <div class="form-horizontal">
                <section class="content-header">
                    <h1>
                        Account create
                        <small></small>
                    </h1>
                </section>
                <br />

                <div class="card card-primary">
                    <div class="card-header with-border">
                        <h3 class="card-title">New account</h3>
                    </div>
                    <div class="card-body">
                        <div class="panel">

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="form-group">
                                @Html.Label("Email", "Email",
                                htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Email,
                                    new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Email, "",
                                    new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.Label("User name", "User name",
                               htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.UserName,
                                   new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.UserName, "",
                                   new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.Label("Password", "Password",
                               htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.PasswordFor(model => model.Password,
                                   new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Password,
                                   "",
                                   new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.Label("Role", "Role",
                               htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownListFor(x => x.Role, new SelectList(ViewBag.Roles), htmlAttributes: new { @class = "form-control" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save" class="btn btn-default" />
                                    @Html.ActionLink("Back",
                                   "Index", "admin",
                                   null,
                                   new { @class = "btn btn-default" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

WebApplication1/Views/Admin/EditRoles.cshtml
@model WebApplication1.Models.IdentityModels.UserAndRolesDTO
@{
    ViewBag.Title = "EditRoles";
    Layout = "_AdminLayout";
}
@using (Html.BeginForm())
{
    <div class="content-wrapper">
        <div class="card-body">
            <section class="content-header">
                <h1>
                    Roles
                    <small></small>
                </h1>
            </section>


            @Html.AntiForgeryToken()
            <br />
            @Html.ValidationSummary(true,
            "",
            new { @class = "text-danger" })
            <div>
                @Html.ActionLink("Back",
               "EditUser",
               new { UserName = Model.UserName },
               new { @class = "btn btn-default" })
                <input type="submit" value="Add role" class="btn btn-default" />
                @Html.DropDownList("AddRole")
            </div>
            <br />
            <div class="card card-primary">
                <div class="card-header with-border">
                    <h3 class="card-title">All roles</h3>

                    <div class="card-tools pull-right">
                        <button type="button" class="btn btn-card-tool" data-widget="collapse" data-toggle="tooltip"
                                title="Collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-card-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                            <i class="fa fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="card-body">
                    <div class="panel">
                        <table class="table">
                            <tr>
                                <th>
                                    Roles:
                                </th>
                                <th></th>
                            </tr>

                            @foreach (var item in Model.colUserRoleDTO)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.RoleName)
                                    </td>
                                    <td>
                                        @if (!((Model.UserName.ToLower() ==
                                            this.User.Identity.Name.ToLower()) &&
                                            item.RoleName == "Administrator") &&
                                            item.RoleName != "No roles")
                                        {
                                            if (item.RoleName != "No roles")
                                            {
                                                @Html.ActionLink("Delete", "DeleteRole",
                                               new { UserName = item.UserName, RoleName = item.RoleName },
                                                new
                                                {
                                                    onclick =
                                                "Confirm('Are you sure you want to delete this role?');"
                                                })}
                                        }
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

}

WebApplication1/Views/Admin/EditUser.cshtml
@model WebApplication1.Models.IdentityModels.ExpandedUserDTO
@{
    Layout = "_AdminLayout";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @*<input class="hidden" name="OrganizationID" value="@ViewBag.OrganizationID " />*@
    <div class="content-wrapper">
        <div class="card-body">
            <section class="content-header">
                <h1>
                    User Settings
                    <small></small>
                </h1>
            </section>
            <br />

            <div class="card card-primary">
                <div class="card-header with-border">
                    <h3 class="card-title">Настройки пользователя</h3>
                </div>
                <div class="card-body">
                    <div class="panel">


                        <div class="form-horizontal">
                            @Html.ValidationSummary(true,
                           "",
                           new { @class = "text-danger" })

                            <div class="form-group">
                                @Html.Label("User name", "User name",
                               htmlAttributes: new { @class = "control-label col-md-2" })
                                
                                <div class="col-md-10">
                                    @Html.DisplayFor(model => model.UserName,
                                   new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.UserName, "",
                                   new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.Label("Email", "Email",
                               htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Email,
                                   new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Email,
                                   "",
                                   new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.Label("Password", "Password",
                               htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.PasswordFor(model => model.Password,
                                   new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Password,
                                   "",
                                   new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save" class="btn btn-default" />
                                    @Html.ActionLink("Setting up roles", "EditRoles", "admin",
                                   new { UserName = Model.UserName },
                                   new { @class = "btn btn-default" })
                                    @Html.ActionLink("Back",
                                   "Index", "admin",
                                   null,
                                   new { @class = "btn btn-default" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

WebApplication1/Views/Admin/Index.cshtml
@model X.PagedList.IPagedList<WebApplication1.Models.IdentityModels.ExpandedUserDTO>
@using X.PagedList.Mvc.Core
<link href="~/css/PagedList.css" rel="stylesheet" type="text/css" />
@{
    Layout = "_AdminLayout";
}

<div class="content-wrapper">
    <div class="card-body">
        <section class="content-header">
            <h1>
                Administration
                <small></small>
            </h1>
        </section>


        <br />
        <div class="card">
            <div class="card-header with-border">
                <h3 class="card-title">All Users</h3>
            </div>
            <div class="card-body">
                <div class="panel">
                    <br />
                    <p>
                        @Html.ActionLink("Create account", "Create", "Admin", null, new { @class = "btn btn-primary" })
                        @Html.ActionLink("Edit roles", "ViewAllRoles", "Admin", null, new { @class = "btn btn-primary" })
                        @Html.ActionLink("Back", "Index", "Home", null, new { @class = "btn btn-primary" })
                    </p>
                    <br />
                    <table class="table" data-page-length='25'>
                        <tr>
                            <th>
                                User name
                            </th>
                            <th>
                                Email
                            </th>
                            <th>
                                Actions
                            </th>
                        </tr>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(ModelItem => item.UserName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Email)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "EditUser", "admin", new { UserName = item.UserName }) |
                                    @Html.ActionLink("Delete", "DeleteUser", "admin", new { UserName = item.UserName },
                                        new { onclick = "return confirm('Are you sure you want to delete this user?');" })
                                </td>
                            </tr>
                        }

                    </table>
                </div>
            </div>

        </div>
    </div>
</div>

WebApplication1/Views/Admin/ViewAllRoles.cshtml
@model IEnumerable<WebApplication1.Models.IdentityModels.RoleDTO>
@{
    ViewBag.Title = "ViewAllRoles";
    Layout = "_AdminLayout";
}

<div class="content-wrapper">
    <div class="card-body">
        <section class="content-header">
            <h1>
                All roles
                <small></small>
            </h1>
        </section>
        <br />


        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="card card-primary">
            <div class="card-header with-border">
                <h3 class="card-title">All roles</h3>
            </div>
            <div class="card-body">
                <div class="panel">
                    <table class="table">
                        <tr>
                            <th>
                                Role
                            </th>
                            <th>
                                Action
                            </th>
                            <th></th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.RoleName)
                                </td>
                                <td>
                                    @if (item.RoleName.ToLower() != "administrator")
                                    {
                                        @Html.ActionLink("Delete", "DeleteUserRole",
                                       new { RoleName = item.RoleName },
                                       new
                                       {
                                           onclick =
                                       "Confirm('Are you sure you want to delete this role?');"
                                       })
                                    }
                                </td>

                            </tr>
                        }

                    </table>

                </div>
                <p>
                    @Html.ActionLink("Back", "Index","admin", null, new { @class = "btn btn-default" })
                    @Html.ActionLink("Add role", "AddRole","admin", null, new { @class = "btn btn-default" })
                </p>
            </div>

        </div>
    </div>
</div>